import type { EventIcon } from '@superagent/client';
import {
  ArrowRightLeft,
  BellRing,
  CircleCheck,
  CircleDot,
  CircleX,
  FilePlus2,
  Flag,
  Hand,
  type LucideIcon,
  MessageSquareText,
  Pencil,
  Send,
  ShieldCheck,
  ShieldQuestion,
  ShieldX,
  Sparkles,
  UserRound,
} from 'lucide-react';

/** The web app's icon for each kind of event (`describeEvent`, in `@superagent/client`, names them). */
export const EVENT_ICONS: Record<EventIcon, LucideIcon> = {
  ArrowRightLeft,
  BellRing,
  CircleCheck,
  CircleDot,
  CircleX,
  FilePlus2,
  Flag,
  Hand,
  MessageSquareText,
  Pencil,
  Send,
  ShieldCheck,
  ShieldQuestion,
  ShieldX,
  Sparkles,
  UserRound,
};
